

upgrade:
	../../main.py upgrade

migrate:
	../../main.py migrate --message "the third mig"

setup:
	../../main.py setup csx

rollback:
	../../main.py rollback

dryrun:
	../../main.py dryrun --runtime csx
